[build]
  command = "npm run build && npm run move"
  publish = "dist"
  environment:
    - SHOPIFY_API_ENDPOINT
    - SHOPIFY_STOREFRONT_API_TOKEN

[dev]
  command = "npm run dev"
  framework = "#custom"
  port = 8888
  targetPort = 3000
  autoLaunch = true

[functions]
  directory = "functions/"
